### ISSUE TITLE
improve model

### ISSUE THREAD

**Issue by de-code** [elifesciences/sciencebeam-gym#1]
The model is currently based on the [pix2pix](https://phillipi.github.io/pix2pix/) model.

One optional extension is to use separate channels per annotation (configured in `color_map.conf`).
However, the model needs to be amended further to make that work correctly (in progress).

I subsequently found this recent [SegAN: Adversarial Network with Multi-scale $L_1$ Loss for Medical Image Segmentation](https://arxiv.org/abs/1706.01805) paper which uses a similar approach. It appears to be using separate discriminators (which may not scale so well). Instead we may want to share weights.

A previous paper, [Semi and Weakly Supervised Semantic Segmentation Using Generative Adversarial Network](https://arxiv.org/abs/1703.09695) may also be interesting. Although it doesn't use the term discriminator in the traditional sense (as detailed in the paper itself).

**Comment by KayShenClarivate** [comment]
Is the current model available for download anywhere? Thanks!

**Comment by de-code** [comment]
> Is the current model available for download anywhere? Thanks!

Hi, no, not currently. I would recommend re-training the model. In the previous experiments it was only training for about 30 minutes on a K80 GPU.
