### ISSUE TITLE
error while running preprocess.sh

### ISSUE THREAD

**Issue by developerpawandeep** [elifesciences/sciencebeam-gym#220]
!bash ./preprocess.sh

error:
USE_CLOUD: false
ARGS: 
usage: preprocessing_pipeline.py [-h] --data-path DATA_PATH
                                 (--lxml-path LXML_PATH | --pdf-path PDF_PATH | --pdf-xml-file-list PDF_XML_FILE_LIST)
                                 [--limit LIMIT] [--save-lxml] [--save-svg]
                                 [--save-png] [--png-dpi PNG_DPI]
                                 [--image-width IMAGE_WIDTH]
                                 [--image-height IMAGE_HEIGHT]
                                 [--save-block-png] [--color-map COLOR_MAP]
                                 [--xml-path XML_PATH]
                                 [--xml-mapping-path XML_MAPPING_PATH]
                                 [--pages PAGES] [--save-tfrecords]
                                 [--min-annotation-percentage MIN_ANNOTATION_PERCENTAGE]
                                 [--annotation-evaluation-csv ANNOTATION_EVALUATION_CSV]
                                 [--output-path OUTPUT_PATH] [--cloud]
                                 [--runner RUNNER] [--project PROJECT]
                                 [--num-workers NUM_WORKERS]
                                 [--max-workers MAX_NUM_WORKERS]
                                 [--job-name JOB_NAME]
                                 [--job-name-suffix JOB_NAME_SUFFIX]
preprocessing_pipeline.py: error: argument --limit: invalid int value: ''
usage: preprocessing_pipeline.py [-h] --data-path DATA_PATH
                                 (--lxml-path LXML_PATH | --pdf-path PDF_PATH | --pdf-xml-file-list PDF_XML_FILE_LIST)
                                 [--limit LIMIT] [--save-lxml] [--save-svg]
                                 [--save-png] [--png-dpi PNG_DPI]
                                 [--image-width IMAGE_WIDTH]
                                 [--image-height IMAGE_HEIGHT]
                                 [--save-block-png] [--color-map COLOR_MAP]
                                 [--xml-path XML_PATH]
                                 [--xml-mapping-path XML_MAPPING_PATH]
                                 [--pages PAGES] [--save-tfrecords]
                                 [--min-annotation-percentage MIN_ANNOTATION_PERCENTAGE]
                                 [--annotation-evaluation-csv ANNOTATION_EVALUATION_CSV]
                                 [--output-path OUTPUT_PATH] [--cloud]
                                 [--runner RUNNER] [--project PROJECT]
                                 [--num-workers NUM_WORKERS]
                                 [--max-workers MAX_NUM_WORKERS]
                                 [--job-name JOB_NAME]
                                 [--job-name-suffix JOB_NAME_SUFFIX]
preprocessing_pipeline.py: error: argument --limit: invalid int value: ''

**Comment by developerpawandeep** [comment]
How to pass these arguments, i tried adding additional .config file but file paths are still confusing.

**Comment by iamrishab** [comment]
You just need to provide `TRAIN_FILE_LIMIT` and `EVAL_FILE_LIMIT` values in `prepare-shell.sh` file which is empty by default. All the values while running `preprocess.sh` are loaded from `prepare-shell.sh` , containing the default values.

**Comment by de-code** [comment]
Apologies, I only just noticed the issue.

`preprocess.sh` should import `prepare-shell.sh`, which in turn loads `.config` if present.

i.e. you could also just run `source prepare-shell.sh` to make the variables available in your shell.
